import { StyleSheet } from 'react-native';
import { Platform, Dimensions } from 'react-native';
import { SIZES, COLORS } from '../../сonstants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
  },
  nextButtonWrapper: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    right: 0,
  },
  nextBtn: {
    fontWeight: '500',
    width: '100%',
    fontSize: 15,
    lineHeight: 36,
    backgroundColor: '#FF3B30',
    textAlign: 'center',
    color: 'white',
    paddingTop: 7,
    paddingBottom: 7,
    fontFamily: Platform.OS === 'ios' ? 'SF Compact Display' : 'SFMedium',
  },
  inputInner: {
    borderWidth: 1,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    position: 'relative',
    marginTop: 5,
    marginBottom: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  inputTitle: {
    position: 'absolute',
    top: 3,
    left: 15,
    paddingLeft: 5,
    paddingRight: 5,
    color: COLORS.darkGray,
  },
  input: {
    flex: 1,
    height: 50,
    color: COLORS.black,
  },
  fieldsWrapper: {
    zIndex: 2,
    position: 'absolute',
    top: 5,
    left: 0,
    width: '100%',
    paddingLeft: 15,
    paddingRight: 15,
  },
  mapStyle: {
    width: '100%',
    height: Platform.OS === 'ios' ? Dimensions.get('window').height - 70 : SIZES.height - 180,
    zIndex: 0,
  },
  mapInside: {
    position: 'absolute',
    top: SIZES.height - 350,
    left: 0,
  },
  mapTypeIcon: {
    width: '100%',
    flex: 1,
    resizeMode: 'contain',
  },
  mapPosIcon: {
    width: '100%',
    flex: 1,
    resizeMode: 'contain',
    opacity: 0.7,
  },
  mapTypeCurrPos: {
    position: 'absolute',
    top: Platform.OS !== 'ios' ? SIZES.height - 320 : SIZES.height - 250,
    right: 12,
    width: 38,
    height: 38,
    backgroundColor: COLORS.primary,
    opacity: 0.8,
    padding: 5,
    borderRadius: 2,
    overflow: 'hidden',
    elevation: 1,
  },
  mapTypeIconWrap: {
    position: 'absolute',
    bottom: 80,
    left: 15,
    width: 50,
    height: 50,
  },
  lottie: {
    width: Platform.OS !== 'ios' ? 200 : 50,
    height: Platform.OS !== 'ios' ? 200 : 50,
  },
  lottieWrapper: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 2,
    top: 0,
    left: 0,
  },
});
