import { StyleSheet } from 'react-native';
import { SIZES, COLORS } from '../../../сonstants';
import { Platform } from 'react-native';

export const styles = StyleSheet.create({
  headerInner: {
    borderTopWidth: 1,
    borderColor: COLORS.gray,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    height: 50,
  },
  headerImageWrapper: {
    width: '10%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headerBrandSearchImage: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
  },
  headerBackInner: {
    width: '10%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  headerBackImage: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
  headerInputInner: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerSearchInput: {
    width: '90%',
  },
  headerSearchImage: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    paddingBottom: 50,
    zIndex: 1,
  },
  scroll: {
    flexGrow: 1,
  },
  itemInner: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    paddingBottom: SIZES.padding,
    paddingTop: SIZES.padding,
    marginBottom: 10,
  },
  itemTitle: {
    flex: 1,
    //borderWidth: 1,
    marginLeft: 18,
  },
  itemCheckedImage: {
    //borderWidth: 2,
    //width: '100%',
    height: 10,
    resizeMode: 'contain',
  },
  searchErrorInner: {
    width: '100%',
    backgroundColor: COLORS.brightRed,
    overflow: 'hidden',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: COLORS.red,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: SIZES.padding,
    paddingBottom: SIZES.padding,
    paddingLeft: 25,
    paddingRight: 25,
  },
  searchErrorText: {
    textAlign: 'center',
    color: COLORS.red,
  },
  modalViewWrapper: {
    backgroundColor: COLORS.substrate,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalViewWrapperContent: {
    backgroundColor: COLORS.primary,
    borderRadius: 5,
    overflow: 'hidden',
    paddingTop: 23,
    paddingBottom: 16,
    paddingLeft: 35,
    paddingRight: 35,
    width: '92%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    color: COLORS.black,
    textAlign: 'center',
    paddingBottom: 10,
  },
  modalTouchableInner: {
    paddingTop: 10,
    paddingBottom: 10,
    width: '100%',
    flexDirection: 'column',
  },
  modalBtnInner: {
    marginBottom: SIZES.padding,
  },
  modalBtn: {
    textAlign: 'center',
    color: COLORS.red,
    paddingTop: 7,
    paddingBottom: 7,
    borderWidth: 1,
    borderColor: COLORS.red,
    borderRadius: SIZES.radius,
  },
  modalCancel: {
    textDecorationLine: 'underline',
    color: '#0E8BFF',
    textAlign: 'center',
  },
  inputInner: {
    width: '100%',
    borderWidth: 1,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    position: 'relative',
    marginTop: 5,
    marginBottom: 5,
    borderColor: COLORS.gray,
  },
  inputTitle: {
    position: 'absolute',
    top: 3,
    left: 15,
    paddingLeft: 5,
    paddingRight: 5,
  },
  input: {
    height: 50,
  },
  inputError: {
    paddingBottom: 10,
    color: COLORS.red,
  },
  addButtonWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  addBtn: {
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.red,
    textAlign: 'center',
    color: COLORS.red,
    paddingTop: 7,
    paddingBottom: 7,
  },
  lottie: {
    width: Platform.OS !== 'ios' ? 200 : 50,
    height: Platform.OS !== 'ios' ? 200 : 50,
  },
  logo: {
    width: 25,
    height: '100%',
    resizeMode: 'contain',
  },
});
