import { StyleSheet, Platform } from 'react-native';
import { SIZES, COLORS, theme } from '../../../сonstants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    paddingTop: SIZES.padding,
  },
  scroll: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  inputInner: {
    borderWidth: 1,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    position: 'relative',
    marginTop: 5,
    marginBottom: 5,
    borderColor: COLORS.gray,
  },
  inputText: {
    paddingTop: SIZES.padding,
    paddingBottom: SIZES.padding,
    color: COLORS.darkGray,
  },
  wprInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  errorMessage: {
    paddingBottom: 10,
    color: COLORS.red,
    textAlign: 'center',
  },
  nextButtonWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  nextBtn: {
    backgroundColor: COLORS.red,
    textAlign: 'center',
    color: COLORS.primary,
    paddingTop: 7,
    paddingBottom: 7,
  },
  fieldIconRight: {
    width: 7,
    height: 13,
  },
  photoDelete: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: COLORS.primary,
    padding: 12,
    overflow: 'hidden',
    borderRadius: 100,
  },
  photoPickerInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 5,
    marginVertical: 10,
  },
  photoPickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.red,
    paddingLeft: SIZES.padding,
    paddingRight: SIZES.padding,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: SIZES.radius,
    width: '49%',
  },
  photoPickerText: {
    color: COLORS.red,
    paddingLeft: 12,
  },
  photoInner: {
    width: '100%',
    paddingBottom: 5,
    paddingTop: 5,
    position: 'relative',
  },
  comment: {
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: 10,
    marginBottom: 15,
    paddingHorizontal: 15,
  },
  photoSurface: {
    marginRight: 8,
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: '#cccccc33',
    width: 240,
    height: 160,
  },
  modalViewWrapper: {
    backgroundColor: COLORS.substrate,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalViewWrapperContent: {
    backgroundColor: COLORS.primary,
    borderRadius: 5,
    overflow: 'hidden',
    paddingTop: 23,
    //paddingBottom: 16,
    //paddingHorizontal: 35,
    width: '92%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    color: COLORS.black,
    textAlign: 'center',
    paddingBottom: 20,
    paddingHorizontal: 35,
  },
  modalTouchableInner: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SIZES.padding,
    paddingBottom: SIZES.padding,
    marginTop: 20,
  },
  modalText: {
    textDecorationLine: 'underline',
    paddingHorizontal: 25,
    paddingVertical: 15,
  },
  lottie: {
    width: Platform.OS !== 'ios' ? 200 : 50,
    height: Platform.OS !== 'ios' ? 200 : 50,
  },
  modalBtn: {
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 20,
    width: '48%',
    flex: 1,
    alignItems: 'center',
  },
  modalBtnText: {
    ...theme.FONTS.body_R_R_14,
    color: COLORS.red,
  },
  modalBtnPrimary: {
    backgroundColor: COLORS.red,
    borderRadius: SIZES.radius,
    color: 'white',
  },
});
