import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';
import { SIZES } from '../../сonstants';

export const styles = StyleSheet.create({
  wrapper: {
    width: '100%',
    flex: 1,
  },
  container: {
    width: '100%',
    flex: 1,
    // paddingLeft: 15,
    // paddingRight: 15,
  },
  scroll: {
    width: '100%',
    flexGrow: 1,
    paddingBottom: 70,
  },
  tabContainer: {
    paddingLeft: 15,
    paddingRight: 15,
    //backgroundColor: 'red',
    //flexGrow: 1,
  },
  warning: {
    backgroundColor: 'rgba(251, 67, 67, 0.1)',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#FB4343',
    paddingLeft: 18,
    paddingRight: 18,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    color: '#FB4343',
    paddingTop: 18,
    paddingBottom: 18,
    fontWeight: '400',
    fontFamily: Platform.OS === 'ios' ? 'SF Compact Display' : 'SF',
  },
  title: {
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'SF Compact Display' : 'SFBold',
    paddingTop: 20,
  },
  dowloadFile: {
    color: 'red',
    borderWidth: 1,
    borderColor: 'red',
    borderRadius: 10,
    textAlign: 'center',
    paddingTop: 2,
    paddingBottom: 2,
    marginTop: 5,
    marginBottom: 15,
  },
  fileExistInner: {
    paddingTop: 5,
    paddingBottom: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fileExistName: {
    flex: 1,
    paddingRight: SIZES.padding,
  },
  deleteFile: {
    color: 'red',
    borderWidth: 1,
    borderColor: 'red',
    borderRadius: 10,
    textAlign: 'center',
    paddingTop: 2,
    paddingBottom: 2,
    paddingHorizontal: SIZES.padding,
  },
  nextButtonWrapper: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    right: 0,
  },
  nextBtn: {
    fontWeight: '500',
    width: '100%',
    fontSize: 15,
    lineHeight: 36,
    backgroundColor: '#FF3B30',
    textAlign: 'center',
    color: 'white',
    paddingTop: 7,
    paddingBottom: 7,
    fontFamily: Platform.OS === 'ios' ? 'SF Compact Display' : 'SFMedium',
  },
  modalViewWrapper: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalViewWrapperContent: {
    backgroundColor: 'white',
    borderRadius: 5,
    overflow: 'hidden',
    paddingTop: 23,
    paddingBottom: 16,
    paddingLeft: 35,
    paddingRight: 35,
    width: '92%',
  },
  modalTitle: {
    //fontFamily: Platform.OS === 'ios' ? 'Roboto' : 'RobotoRegular',
    fontWeight: '400',
    fontSize: 16,
    color: '#333333',
    lineHeight: 23,
    textAlign: 'center',
    paddingBottom: 20,
  },
  modalTouchableInner: {
    paddingTop: 10,
    paddingBottom: 10,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  modalText: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'SF Compact Display' : 'SF',
    fontWeight: '400',
    textDecorationLine: 'underline',
  },
  modalList: {
    textAlign: 'left',
    //fontFamily: Platform.OS === 'ios' ? 'Roboto Light' : 'RobotoLight',
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 24,
  },
  radioGroupContainer: {
    flexWrap: 'wrap',
    flex: 1,
    justifyContent: 'space-between',
  },
  lottie: {
    width: Platform.OS !== 'ios' ? 200 : 50,
    height: Platform.OS !== 'ios' ? 200 : 50,
  },
});
