export const LOGIN_TOKEN = 'LOGIN_TOKEN';
export const CREATED_REPORT_ID = 'CREATED_REPORT_ID';
export const OPEN_SCREEN = 'APP/OPEN_SCREEN';
export const IS_MENU_OPEN = 'IS_MENU_OPEN';
export const REPORT_TYPE = 'REPORT_TYPE';
export const SECTION_LIST = 'SECTION_LIST';
export const REPORT_END_MODAL = 'REPORT_END_MODAL';
export const USER_INFO = 'USER_INFO';
export const UNFILLED_FIELDS = 'UNFILLED_FIELDS';

export const INIT_REGIONS = 'REGIONS/INIT_REGIONS';
export const SET_REGION_CITIES = 'REGIONS/SET_REGION_CITIES';
export const SET_REGION_COLLAPSED = 'REGIONS/TOGGLE_REGION_COLLAPSED';
export const ADD_CHOSEN_REGION = 'REGIONS/ADD_CHOSEN_REGION';
export const DELETE_CHOSEN_REGION = 'REGIONS/DELETE_CHOSEN_REGION';
export const ADD_CHOSEN_CITY = 'REGIONS/ADD_CHOSEN_CITY';
export const DELETE_CHOSEN_CITY = 'REGIONS/DELETE_CHOSEN_CITY';
export const CLEAR_CHOSEN = 'REGIONS/CLEAR_CHOSEN';
export const ADD_CITY_TO_REGIONS_SHOWN = 'REGIONS/ADD_CITY_TO_REGIONS_SHOWN';
export const CLEAR_REGIONS_SHOWN = 'REGIONS/CLEAR_REGIONS_SHOWN';
export const SET_REGIONS_SHOWN_TO_NO_SEARCH_MODE = 'REGIONS/SET_REGIONS_SHOWN_TO_NO_SEARCH_MODE';
export const ADD_REGION_TO_REGIONS_SHOWN = 'REGIONS/ADD_REGION_TO_REGIONS_SHOWN';

export const INIT_TIRES = 'TIRES/INIT_TIRES';
export const ADD_TIRE = 'TIRES/ADD_TIRE';
export const TURN_ON_MODE_HALF = 'TIRES/TURN_ON_MODE_HALF';
export const TURN_ON_MODE_ALL = 'TIRES/TURN_ON_MODE_ALL';
export const TURN_ON_MODE_NONE = 'TIRES/TURN_ON_MODE_NONE';
export const CLEAR_TIRES = 'TIRES/CLEAR';

export const SET_FIELD = 'TECH_CHAR/SET_FIELD';

export const SET_BRANDS_LIST = 'LISTS/SET_BRANDS_LIST';

export const SET_POPULAR_BRANDS_LIST = 'LISTS/SET_POPULAR_BRANDS_LIST';

export const SET_TIRES_BRANDS_LIST = 'LISTS/SET_TIRES_BRANDS_LIST';

export const SET_REPORTS_LIST = 'REPORTS/SET_REPORTS_LIST';

export const ADD_TO_FAVORITES = 'REPORTS/ADD_TO_FAVORITES';

export const REMOVE_FROM_FAVORITES = 'REPORTS/REMOVE_FROM_FAVORITES';

export const DELETE_REPORT = 'REPORTS/DELETE_REPORT';
